name: flutter_job
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  surf_lint_rules: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  dart_code_metrics: ^4.19.2

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900
        - asset: fonts/Roboto/Roboto-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/Roboto/Roboto-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-ThinItalic.ttf
          style: italic
          weight: 100

